export const CONTRACT_STATUS_VALUES = {
  TERMINADO: 0,
  EN_CURSO: 1,
  PROGRAMADO: 2
}

export const CONTRACT_STATUS_LABELS = {
  [CONTRACT_STATUS_VALUES.TERMINADO]: 'Terminado',
  [CONTRACT_STATUS_VALUES.EN_CURSO]: 'En curso',
  [CONTRACT_STATUS_VALUES.PROGRAMADO]: 'Programado'
}

export const DATE_FORMAT = 'DD/MM/YYYY'
